### ISSUE TITLE
Invalid Values being created in daemon.json

### ISSUE THREAD

**Issue by Serienmorder** [ericsysmin/ansible-collection-docker#2]
ansible version: 2.9
target: Centos 7

When providing the following playbook:

    - hosts: 192.168.11.140
      become: yes
      roles:
       - role: ericsysmin.docker.docker
         vars:
           docker_users:
             - dave
           docker_insecure_registries: 10.10.3.144:9081
           docker_edition: 'ce'

This is what appears in daemon.json:

    {
        "insecure-registries": "10.10.3.144:9081"
    }

Proper syntax for the value of the key is the following:

    {
        "insecure-registries": ["10.10.3.144:9081"]
    }

**Comment by Serienmorder** [comment]
Alternatively suggesting adding documentation that items should be passed like this:
    docker_insecure_registries: "[10.10.3.144:9081]"

**Comment by ericsysmin** [comment]
@Serienmorder you should be passing it as this
```
- hosts: 192.168.11.140
  become: yes
  roles:
   - role: ericsysmin.docker.docker
     vars:
       docker_users:
         - dave
       docker_insecure_registries: 
         - 10.10.3.144:9081
       docker_edition: 'ce'
```
